config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:index, :show, :update] do
    collection do
      get '/profile' => 'users#profile'
      put '/update_profile' => 'users#update_profile'
    end
  end
  resources :opinions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
root "opinions#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  scope :most_recent, -> { order(created_at: :desc) }
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :author, class_name: 'User'

  validates :Text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: { minimum: 3 }
  validates :email, presence: true, length: { minimum: 10 }

  has_many :opinions, foreign_key: 'author_id', class_name: 'Opinion', dependent: :destroy

  has_many :friendships, foreign_key: 'followed_id', class_name: 'Friendship'
  has_many :followers, through: :friendships, source: :follower

  has_many :inverse_friendships, foreign_key: 'follower_id', class_name: 'Friendship'
  has_many :followed_users, through: :inverse_friendships, source: :followed
  has_one_attached :photo

  scope :most_recent, -> { order(created_at: :desc) }
end

# Users who are yet to be followed
def pending_followers
  partners = [].concat(current_user.followers, current_user.followed_users).map(&:id)
  User.all.reject { |user| current_user.id == user.id || user.id.in?(partners) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    id1 = params[:ids][:id1]
    id2 = params[:ids][:id2]
    @friendship = Friendship.new(followed_id: id1, follower_id: id2)
    @friendship.save
    redirect_to users_path
  end

  def destroy
    friendship = Friendship.find(params[:friendship_id])
    friendship.destroy
    redirect_to user_path(current_user.id)
  end

  def update
    friendship = Friendship.find(params[:friendship_id])
    current_user
    friendship.update(confirmed: true)
    redirect_to user_path(friendship.follower_id)
  end

  # def create
  #   @friendship = Current.user.friendships.new(followed_id: params[:user_id])
  #   if @friendship.save
  #       flash[:notice] = "You are following #{User.find(params[:user_id]).full_name}"
  #   else
  #       flash[:alert] = 'Something went wrong ...'
  #   end
  #   redirect_to root_path
  # end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /opinions or /opinions.json
  def index
    @opinions = Opinion.all.order('created_at DESC')
    @opinion = Opinion.new
  end

  # GET /opinions/1 or /opinions/1.json
  def show; end

  # GET /opinions/new
  def new
    @opinion = current_user.opinions.build
  end

  # GET /opinions/1/edit
  def edit; end

  # POST /opinions or /opinions.json
  def create
    @opinion = current_user.opinions.build(opinion_params)

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to root_path, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /opinions/1 or /opinions/1.json
  def update
    respond_to do |format|
      if @opinion.update(opinion_params)
        format.html { redirect_to @opinion, notice: 'Opinion was successfully updated.' }
        format.json { render :show, status: :ok, location: @opinion }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opinions/1 or /opinions/1.json
  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_opinion
    @opinion = Opinion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def opinion_params
    params.require(:opinion).permit(:Text)
  end
end

app/controllers/registration_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:user).permit(:username, :fullname, :email, :password, :password_confirmation)
	end

	def acount_update_params 
		params.require(:user).permit(:username, :fullname, :email, :password, :password_confirmation, :current_password)
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :fullname, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.reject { |user| user.id == current_user.id }
  end

  def show
    @user = User.includes(:opinions, :followers, :followed_users).find(params[:id])
  end

  def update
    following_user = Friendship.new(follower_id: current_user.id, followed_id: params[:id])

    if following_user.save
      redirect_to user_path(params[:id])
    else
      flash.now = 'An error occured'
    end
  end

  def update_profile
    if current_user.update(account_update_params.except(:photo))
      current_user.photo.attach(account_update_params[:photo])
      redirect_to user_path(current_user)
    else
      render 'profile'
    end
  end

  def profile
    @user = current_user
  end

  private

  def account_update_params
    params.require(:user).permit(:username, :fullname, :email,
                                 :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_follow_btn?(id)
    user_to_add = id || params[:id]
    already_following = Friendship.where(follower_id: current_user.id, followed_id: user_to_add).first
    puts already_following, 'following!!!!', user_to_add.to_i != current_user.id && already_following.nil?

    user_to_add.to_i != current_user.id && already_following.nil?
  end

  def display_follow_btn(_user)
    button_to 'Follow', user_path(@user), method: :patch, class: 'badge badge-primary' if display_follow_btn?(@user.id)
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
    <div class="navbar-brand">
    <%= link_to root_path, class: "b=navbar-items" do %>
      <h1 class="title is-5">Twitter</h1>
    <% end %>
    <div class="navbar-burger burger" data-target="navbarExample">
    
    </div>
    </div>

    <div id="navbarExample" class="navbar-menu">
    <div class="navbar-end">
    <div class="navbar-item">
    <div class="field is-grouped">
    <p class="control">
    <%= link_to 'New Opinion', root_path, class: "button is-info is-inverted" %>
    </p>
    <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.username, profile_users_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
            </p>
						<p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>
            </div>
					</div>
				</div>
			</div>
  	</nav>

    <%= yield %>
  </body>
</html>

app/views/opinions/_feed.html.erb
<div class="column is-half d-flex">
<div class="tabs">
			<ul>
				<li class="is-active"><a>Opionions</a></li>
				<li><a>Followers</a></li>
				<li><a>Following</a></li>
			</ul>
			</div>
<% if user_signed_in? %>
	<article class="media box">
		<figure class="media-left">
			<p class="image is-64x64 rounded">
				<img src="https://bulma.io/images/placeholders/64x64.png"
			</p>
		</figure>
		<div class="media-content">
			 <%= render 'opinions/form' %>
		</div>
	</article>
<% end %>
<% @opinions.each do | opinion | %>
  <div class="box">
  	<article class="media">
  		<div class="media-left">
  			<figure class="image is-64x64 rounded">
              <img src="https://bulma.io/images/placeholders/64x64.png"
  			</figure>
  		</div>
  		<div class="media-content">
  			<div class="content">
  				<strong><%= opinion.author.username %></strong><br />
  				<small><%= opinion.author.fullname %></small><br/>
  				<p><%= opinion.Text %></p>
  			</div>
			<% if user_signed_in? %>
  			<nav class="level">
  				<div class="level-left is-mobile">
  					<%= link_to opinion, class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to edit_opinion_path(opinion), class: "level-item" do %>
  					  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
  					<% end %>
  					<%= link_to opinion, method: :delete, data: { confirm: "Are you sure you want to delete this opinion?" } do %>
  							<span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
  					<% end %>
  				</div>
  			</nav>
			<% end %>
  		</div>
  	</article>
  </div>
<% end %>
</div>

app/views/opinions/_form.html.erb
<%= simple_form_for(@opinion) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :Text, label: "What's your opinion", input_html: { class: "textarea "}, wrapper: false, label_html: {class: "label"}, placeholder: "Share your opinion...", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
  <% end %>

app/views/opinions/_menu.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Menu</p>
		<a class="panel-block">
			Home
		</a>
		<a class="panel-block">
			People
		</a>
	</nav>
</div>

app/views/opinions/_profile.html.erb
<div class="sidenav" >
	<nav class="panel" id="profile">
		
		<div class="panel-block">
		<%= link_to user_path(current_user) do %>
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64 rounded">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.username) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							
							<small><%= current_user.fullname %></small>
						</p>
					</div>
				</div>
			</article>
		<% end %>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Opinions</p>
						<p class="title is-6"><%= current_user.opinions.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6"><%= current_user.followed_users.count %></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6"><%= current_user.followers.count %></p>
					</div>
				</div>
			</div>
		</div>
		<div class="menu">
		<ul class="menu-list">
			
			<%= link_to 'Home', root_path, class: "mb-3 pl-1" %>
			<%= link_to 'People', users_path, class: "mb-3 pl-1" %>
			
		</div>
  		</ul>
	</nav>
</div>

app/views/opinions/_who-to-follow.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>
	<strong><% pending_followers.each do |user| %></strong>
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<%= link_to user_path(user) do%>
			<div class="media-content">
				<div class="content">
					<p>
						<%= user.username %>
						<%= link_to 'Follow', user_path(user), method: :patch, class: 'badge badge-primary ml-3' %>
					</p>	
				</div>
			<% end %>
			</div>
		</article>
	</div>
	<% end %>
	</nav>
</div>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/index.html.erb
<section class="section">
<div class="container">
  <div class="columns">
   <% if user_signed_in? %>
    <%= render 'profile' %>
   <% else %>
    <%= render "menu" %>
   <% end %>
    <%= render "feed" %>
    <% if user_signed_in? %>
    <%= render "who-to-follow" %>
    <% end %>
  </div>
</div>
</section>

app/views/opinions/new.html.erb
<h1>New Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Back', opinions_path %>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @opinion.Text %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>

app/views/users/index.html.erb
<div class="panel">
<p class="panel-heading">Users</p>
    <% @users.each do |user| %>
        <div class="panel-block">
        
            
            <article class="media">
                <div class="media-left">
                    <figure class="image is-32x32">
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    </figure>
                </div>
            
                <div class="panel-block">
                <div class="media-content">
                    <div class="content">
                    <%= link_to user_path(user) do%>
                        <p>
                            <%= user.username %>
                        </p>	
                    </div>
                </div>
                <% end %>
            </article>
        </div>
        
    <% end %>
</div>

app/views/users/profile.html.erb
<section class="section">

  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        
      <h2 class="title is-2">Edit <%= @user.to_s.humanize %></h2>
      <%= simple_form_for(@user, url: update_profile_users_path, html: { method: :put }) do |f| %>
        <%= f.error_notification %>

          <div class="field">
            <div class="control">
              <%= f.input :username, required: true, autofocus: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= f.input :fullname, required: true,  input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
            </div>
          </div>

          <div class="field">
            <div class="control">
              <%= f.input :email, required: true, input_html: { class: "input"}, wrapper: false, label_html: { class: "label" } %>
            </div>
          </div>
          
        <div class="mb-3">
        <%= f.file_field :photo, class:"form-control" %>
        </div>
   
        <%= f.button :submit, "Update", class:"button is-info" %>
     
      <% end %>
   
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
<div class="container">
<div class="columns">
<div class="column is-one-quarter" >
	<nav class="panel" id="profile">
		
		<div class="panel-block">
		<%= link_to user_path(current_user) do %>
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.username) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							
							<small><%= current_user.fullname %></small>
						</p>
					</div>
				</div>
			</article>
		<% end %>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Opinions</p>
						<p class="title is-6"><%= current_user.opinions.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6"><%= current_user.followed_users.count %></p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6"><%= current_user.followers.count %></p>
					</div>
				</div>
			</div>
		</div>
		<div class="menu">
		<ul class="menu-list">
			
			<%= link_to 'Home', root_path, class: "mb-3 pl-1" %>
			<%= link_to 'People', users_path, class: "mb-3 pl-1" %>
			
		</div>
  		</ul>
	</nav>
</div>

<div class="column is-half">
    
			<figure class="is-fullwidth">
            <% if @user.photo.attached? %>
				<img src="<%= url_for(@user.photo) %>" >
			<% else %>
			<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.username) %>
			<% end %>

			</figure>
			<div class="tabs">
			<ul>
				<li class="is-active"><a>Opionions</a></li>
				<li><a>Pictures</a></li>
				<li><a>Followers</a></li>
				<li><a>Following</a></li>
			</ul>
			</div>
            <div class="card-body">
                <h6>My Opinions</h6><hr>
                <div class= "text-muted">
                    <% @user.opinions.each do |opinion| %>
                        <div class="card-body text-muted">
                            <p> <%= opinion.Text %> <span><%= link_to 'Delete', opinion_path(opinion), method: :delete, class: 'btn btn-primary btn-sm ml-5 fsz-2' %></span></p>
                        </div><hr>
                    <% end %>
                </div>
            </div>
</div>

<div class="box">

			<div class="columns is-mobile is-centered">
			<div class="column is-half">
			<p class="bd-notification is-primary">
			<% if @user.photo.attached? %>
			<img class="image is-rounded" src="<%= url_for(@user.photo) %>" >
			<% else %>
			<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.username) %>
			<% end %>
			</p>
			</div>
			</div>
			
			<div class="columns is-mobile is-centered">
			<div class="column is-half">
				
				<%= @user.fullname %><br>
				<%= display_follow_btn(@user) %>
			</div>
			</div>
			
			<div class="card">
				<div class="card-footer">
					
					<p class="card-footer-item">
					<span><%= @user.opinions.length %>
            		 <a href="#">Opinions </a></span>
					</p>
					<p class="card-footer-item">
					<span><%= @user.followed_users.length %>
            		 <a href="#">Following </a></span>
					</p>
					<p class="card-footer-item">
					<span><%= @user.followers.length %>
            		 <a href="#">Followers </a></span>
					</p>
				</div>
			</div>

          
        <div class="column">
            <div class="tabs is-large">
                <p>Followed By</p>
            </div>
                <div class="card-body"><hr>
                    <% @user.followers.each do |user| %>
                        <div class="card-body is-flex">

                            <%= gravatar_image_tag(current_user.email, class: "image rounded-circle") %>

                        <h4 class="is-text-centered"> <%= user.fullname %> </h4><hr>
                        </div><hr>
                    <% end %>
                </div>

        </div>
</div>


</div>
</div>
</section>